replicaCount: 1

image:
  repository: "<TO_BE_FILLED>"
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081
  labels:
    release: prometheus

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

# Configuration améliorée des health checks pour la base de données
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 90
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

env:
  # Configuration Spring Boot et Eureka
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server:8761/eureka
  - name: MANAGEMENT_TRACING_ENABLED
    value: "false"
  - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
    value: ""
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
  - name: EUREKA_INSTANCE_HOSTNAME
    value: customers-service
  - name: SPRING_BOOT_ADMIN_CLIENT_URL
    value: http://admin-server:9091
  - name: SPRING_BOOT_ADMIN_CLIENT_PREFER_IP
    value: "false"
  - name: SERVER_PORT
    value: "8081"
  - name: SPRING_PROFILES_ACTIVE
    value: "mysql"
  
  # Configuration Hibernate et JPA
  - name: SPRING_JPA_HIBERNATE_DDL_AUTO
    value: "update"
  - name: SPRING_JPA_SHOW_SQL
    value: "false"
  - name: SPRING_JPA_DATABASE_PLATFORM
    value: "org.hibernate.dialect.MySQLDialect"
  
  # Désactivation du tracing
  - name: MANAGEMENT_TRACING_ENABLED
    value: "false"
  - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
    value: ""
    
  # Variables de base de données depuis le secret AWS
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_host
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_password
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_name
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_port

  # Configuration Spring Boot pour forcer l'utilisation des variables d'environnement
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:mysql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&connectTimeout=60000&socketTimeout=60000&autoReconnect=true"
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_user
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_password
  - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
    value: "com.mysql.cj.jdbc.Driver"
    
  # Configuration Hikari pour améliorer la connexion DB
  - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
    value: "60000"
  - name: SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT
    value: "300000"
  - name: SPRING_DATASOURCE_HIKARI_MAX_LIFETIME
    value: "1200000"
  - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
    value: "5"
  - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
    value: "1"
  - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
    value: "30000"

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  port: http
  interval: 15s
  scrapeTimeout: 10s
  additionalLabels:
    release: prometheus
