replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: dockerhub-credentials

nameOverride: ""
fullnameOverride: "api-gateway"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: ""
  domain: "temp.example.com"              

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888/config
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server:8761/eureka
  - name: SPRING_BOOT_ADMIN_CLIENT_URL
    value: http://admin-server:9090
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
  - name: EUREKA_INSTANCE_HOSTNAME
    value: api-gateway
