{{- if .Values.ingress.enabled }}
{{- $secret := lookup "v1" "Secret" "default" "dockerhub-credentials" }}
{{- if $secret }}
{{- $domain := (index $secret.data "domainName" | b64dec) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ $domain | quote }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "api-gateway.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

{{- else }}
{{- fail "Le champ 'domainName' est manquant dans le secret 'dockerhub-credentials'. Assurez-vous qu’il a été bien mis à jour dans AWS Secrets Manager." }}
{{- end }}
{{- end }}
