apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ArseniiT/spring-petclinic-helm-charts.git
    targetRevision: HEAD
    path: customers-service
    helm:
      valueFiles:
        - values.yaml
        - values.secret.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
