replicaCount: 1

image:
  repository: "<TO_BE_FILLED>"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082
  labels:
    release: prometheus

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888/config
  - name: EUREKA_SERVER_URL
    value: http://discovery-server:8761/eureka
  - name: MANAGEMENT_TRACING_ENABLED
    value: "false"
  - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
    value: ""
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
  - name: EUREKA_INSTANCE_HOSTNAME
    value: customers-service
  - name: SPRING_BOOT_ADMIN_CLIENT_URL
    value: http://admin-server:9090
  - name: SPRING_BOOT_ADMIN_CLIENT_PREFER_IP
    value: "true"
  - name: SERVER_PORT
    value: "8082"
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_host
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_password
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_name
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_port

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  port: http
  interval: 15s
  scrapeTimeout: 10s
  additionalLabels:
    release: prometheus
