replicaCount: 1

image:
  repository: "<TO_BE_FILLED>"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "vets-service"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: 
  restart-trigger: "v5"
podLabels: {}

podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8082
  targetPort: 8082
  labels:
    release: prometheus

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: http://discovery-server:8761/eureka
  - name: EUREKA_INSTANCE_HOSTNAME
    value: vets-service
  - name: CONFIG_SERVER_URL
    value: http://config-server:8888/config
  - name: SPRING_BOOT_ADMIN_CLIENT_URL
    value: http://api-gateway:8080
  - name: SPRING_BOOT_ADMIN_DISCOVERY_ENABLED
    value: "true"
  - name: SPRING_BOOT_ADMIN_CLIENT_PREFER_IP
    value: "false"
  - name: MANAGEMENT_TRACING_ENABLED
    value: "false"
  - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
    value: ""
  - name: SPRING_ZIPKIN_ENABLED
    value: "false"
  - name: SPRING_ZIPKIN_BASEURL
    value: ""
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_host
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_password
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_name
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: dockerhub-credentials
        key: db_port

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  port: http
  interval: 15s
  scrapeTimeout: 10s
  additionalLabels:
    release: prometheus
