apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    # repoURL: https://prometheus-community.github.io/helm-charts
    repoURL: prometheus-community
    chart: kube-prometheus-stack
    targetRevision: 56.6.0
    helm:
      values: |
        fullnameOverride: prometheus
        alertmanager.enabled: false
        kubeStateMetrics.enabled: false
        nodeExporter.enabled: false
        pushgateway.enabled: false
        grafana.enabled: false
        prometheus:
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
