fullnameOverride: prometheus

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

server:
  service:
    type: ClusterIP
  ingress:
    enabled: false

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
    resources:
      requests:
        memory: 400Mi


