apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vets-service.fullname" . }}
  labels:
    release: prometheus  # tres importante
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vets-service.name" . }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
  namespaceSelector:
    matchNames:
      - default
