# Valeurs par défaut pour admin-server
# Fichier YAML formaté pour déclarer les variables passées aux templates

# Nombre de répliques pour le ReplicaSet
replicaCount: 1

# Configuration de l'image de conteneur
image:
  repository: "<TO_BE_FILLED>"
  pullPolicy: IfNotPresent
  tag: "latest"

# Secrets pour extraire l'image d'un dépôt privé
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "admin-server"

# Configuration du compte de service
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Annotations et labels du pod
podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# Configuration du service Kubernetes
service:
  type: ClusterIP
  port: 9091
  targetPort: 9091
  labels:
    release: prometheus

# Configuration de l'Ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Limites de ressources
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Configuration des sondes de santé
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 9091
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 9091
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5

# Configuration de l'autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

# Variables d'environnement pour l'application Spring Boot
env:
  - name: SERVER_PORT
    value: "9091"
  - name: SPRING_CLOUD_CONFIG_ENABLED
    value: "false"
  - name: EUREKA_CLIENT_ENABLED
    value: "false"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,prometheus"
  - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
    value: "true"
  - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
    value: "true"
  - name: SPRING_PROFILES_ACTIVE
    value: "default"

# Configuration du ServiceMonitor pour Prometheus
serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  port: http
  interval: 15s
  scrapeTimeout: 10s
  additionalLabels:
    release: prometheus